// <auto-generated />
namespace br.com.LojaVeiculos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class lista_endereco : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lista_endereco));
        
        string IMigrationMetadata.Id
        {
            get { return "201704211429526_lista_endereco"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
